apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::691748761377:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1JLHKBTYQXYK5
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-05T12:51:52Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "847"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: f1d73c3a-2a0e-43e4-b6f1-06588821f5f5
