--- 
apiVersion: v1
data: 
  mapRoles: |
      - groups:
        - system:bootstrappers
        - system:nodes
        rolearn: arn:aws:iam::691748761377:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1RASDROUKIQ28
        username: system:node:{{EC2PrivateDNSName}}
      - groups:
        - system:masters
        rolearn: arn:aws:iam::691748761377:role/UdacityFlaskDeployCBKubectlRole
        username: build
  mapUsers: "[]\n"
kind: ConfigMap
metadata: 
  creationTimestamp: "2020-08-05T16:39:33Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "886"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 83e32b6b-7c43-4630-8c06-0acf7c4b6841
